// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authsvc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetJwtRequest struct {
	ValidityTime         int64    `protobuf:"varint,1,opt,name=validity_time,json=validityTime,proto3" json:"validity_time,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Aud                  []string `protobuf:"bytes,4,rep,name=aud,proto3" json:"aud,omitempty"`
	Sub                  string   `protobuf:"bytes,5,opt,name=sub,proto3" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJwtRequest) Reset()         { *m = GetJwtRequest{} }
func (m *GetJwtRequest) String() string { return proto.CompactTextString(m) }
func (*GetJwtRequest) ProtoMessage()    {}
func (*GetJwtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{0}
}

func (m *GetJwtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJwtRequest.Unmarshal(m, b)
}
func (m *GetJwtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJwtRequest.Marshal(b, m, deterministic)
}
func (m *GetJwtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJwtRequest.Merge(m, src)
}
func (m *GetJwtRequest) XXX_Size() int {
	return xxx_messageInfo_GetJwtRequest.Size(m)
}
func (m *GetJwtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJwtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJwtRequest proto.InternalMessageInfo

func (m *GetJwtRequest) GetValidityTime() int64 {
	if m != nil {
		return m.ValidityTime
	}
	return 0
}

func (m *GetJwtRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetJwtRequest) GetAud() []string {
	if m != nil {
		return m.Aud
	}
	return nil
}

func (m *GetJwtRequest) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

type GetJwtResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJwtResponse) Reset()         { *m = GetJwtResponse{} }
func (m *GetJwtResponse) String() string { return proto.CompactTextString(m) }
func (*GetJwtResponse) ProtoMessage()    {}
func (*GetJwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{1}
}

func (m *GetJwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJwtResponse.Unmarshal(m, b)
}
func (m *GetJwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJwtResponse.Marshal(b, m, deterministic)
}
func (m *GetJwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJwtResponse.Merge(m, src)
}
func (m *GetJwtResponse) XXX_Size() int {
	return xxx_messageInfo_GetJwtResponse.Size(m)
}
func (m *GetJwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJwtResponse proto.InternalMessageInfo

func (m *GetJwtResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetJwtResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{2}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

func (m *RefreshRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{3}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

func (m *RefreshResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ValidateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{4}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateResponse struct {
	Payload              *ValidateResponse_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{5}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetPayload() *ValidateResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ValidateResponse_Payload struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Iss                  string   `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`
	Exp                  int32    `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Sub                  string   `protobuf:"bytes,4,opt,name=sub,proto3" json:"sub,omitempty"`
	Aud                  string   `protobuf:"bytes,5,opt,name=aud,proto3" json:"aud,omitempty"`
	Nbf                  int32    `protobuf:"varint,6,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Iat                  int32    `protobuf:"varint,7,opt,name=iat,proto3" json:"iat,omitempty"`
	Jti                  string   `protobuf:"bytes,8,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse_Payload) Reset()         { *m = ValidateResponse_Payload{} }
func (m *ValidateResponse_Payload) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse_Payload) ProtoMessage()    {}
func (*ValidateResponse_Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2234b631135d89c, []int{5, 0}
}

func (m *ValidateResponse_Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse_Payload.Unmarshal(m, b)
}
func (m *ValidateResponse_Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse_Payload.Marshal(b, m, deterministic)
}
func (m *ValidateResponse_Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse_Payload.Merge(m, src)
}
func (m *ValidateResponse_Payload) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse_Payload.Size(m)
}
func (m *ValidateResponse_Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse_Payload proto.InternalMessageInfo

func (m *ValidateResponse_Payload) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ValidateResponse_Payload) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *ValidateResponse_Payload) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *ValidateResponse_Payload) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *ValidateResponse_Payload) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *ValidateResponse_Payload) GetNbf() int32 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *ValidateResponse_Payload) GetIat() int32 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *ValidateResponse_Payload) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func init() {
	proto.RegisterType((*GetJwtRequest)(nil), "pb.GetJwtRequest")
	proto.RegisterType((*GetJwtResponse)(nil), "pb.GetJwtResponse")
	proto.RegisterType((*RefreshRequest)(nil), "pb.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "pb.RefreshResponse")
	proto.RegisterType((*ValidateRequest)(nil), "pb.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "pb.ValidateResponse")
	proto.RegisterType((*ValidateResponse_Payload)(nil), "pb.ValidateResponse.Payload")
}

func init() {
	proto.RegisterFile("authsvc.proto", fileDescriptor_a2234b631135d89c)
}

var fileDescriptor_a2234b631135d89c = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcb, 0x6e, 0xe2, 0x30,
	0x14, 0x86, 0x31, 0x81, 0x04, 0x0e, 0xd7, 0x31, 0x48, 0x63, 0xa1, 0x59, 0x44, 0x99, 0xc5, 0xb0,
	0x8a, 0x34, 0xcc, 0xa5, 0xeb, 0xae, 0xaa, 0x5e, 0x16, 0x55, 0x8a, 0xba, 0x45, 0x0e, 0x31, 0xc2,
	0x14, 0x92, 0x10, 0x3b, 0xb4, 0xbc, 0x4d, 0xdf, 0xa0, 0x4f, 0xd6, 0x77, 0xa8, 0x1c, 0x27, 0x94,
	0x20, 0x76, 0xdd, 0xd9, 0x9f, 0xff, 0xdf, 0x3e, 0xe7, 0xfc, 0x09, 0x74, 0x68, 0x2a, 0x97, 0x62,
	0x37, 0x77, 0xe3, 0x24, 0x92, 0x11, 0xae, 0xc6, 0xbe, 0xb3, 0x85, 0xce, 0x15, 0x93, 0x37, 0xcf,
	0xd2, 0x63, 0xdb, 0x94, 0x09, 0x89, 0x7f, 0x42, 0x67, 0x47, 0xd7, 0x3c, 0xe0, 0x72, 0x3f, 0x93,
	0x7c, 0xc3, 0x08, 0xb2, 0xd1, 0xd8, 0xf0, 0xda, 0x05, 0x9c, 0xf2, 0x0d, 0xc3, 0xdf, 0xc1, 0x4a,
	0x05, 0x4b, 0x66, 0x3c, 0x20, 0x55, 0x1b, 0x8d, 0xeb, 0x9e, 0xa9, 0xb6, 0xd7, 0x01, 0xee, 0x83,
	0x41, 0xd3, 0x80, 0xd4, 0x6c, 0x63, 0xdc, 0xf4, 0xd4, 0x52, 0x11, 0x91, 0xfa, 0xa4, 0x6e, 0x23,
	0x45, 0x44, 0xea, 0x3b, 0xb7, 0xd0, 0x2d, 0x9e, 0x14, 0x71, 0x14, 0x0a, 0x86, 0x87, 0x50, 0x97,
	0xd1, 0x13, 0x0b, 0xb3, 0xb7, 0x9a, 0x9e, 0xde, 0xa8, 0x4a, 0x12, 0xb6, 0x48, 0x98, 0x58, 0xce,
	0xf4, 0x69, 0x35, 0x3b, 0x6d, 0xe7, 0x70, 0xaa, 0x98, 0xf3, 0x0f, 0xba, 0x9e, 0xde, 0x1f, 0x35,
	0x50, 0xb6, 0xa1, 0x33, 0xb6, 0x3b, 0xe8, 0x1d, 0x6c, 0x5f, 0x2f, 0xe2, 0x17, 0xf4, 0x1e, 0xd5,
	0x78, 0xa8, 0x64, 0x45, 0x15, 0x67, 0x6f, 0x73, 0xde, 0x11, 0xf4, 0x3f, 0x95, 0xf9, 0xc3, 0xff,
	0xc1, 0x8a, 0xe9, 0x7e, 0x1d, 0xd1, 0x20, 0x13, 0xb7, 0x26, 0x3f, 0xdc, 0xd8, 0x77, 0x4f, 0x65,
	0xee, 0xbd, 0xd6, 0x78, 0x85, 0x78, 0xf4, 0x8a, 0xc0, 0xca, 0xe1, 0x71, 0x20, 0xe8, 0x34, 0x10,
	0x2e, 0x44, 0x5e, 0xb5, 0x5a, 0x2a, 0xc2, 0x5e, 0x62, 0x62, 0x64, 0x32, 0xb5, 0x2c, 0x22, 0xaa,
	0x1d, 0x22, 0x2a, 0x62, 0xcc, 0x43, 0xcb, 0x63, 0x0c, 0xfd, 0x05, 0x31, 0xb5, 0x2b, 0xf4, 0x17,
	0xd9, 0xcd, 0x54, 0x12, 0x4b, 0x13, 0x4e, 0xa5, 0x22, 0x2b, 0xc9, 0x49, 0x43, 0xbb, 0x56, 0x92,
	0x4f, 0xde, 0x10, 0xb4, 0x2e, 0x53, 0xb9, 0x7c, 0x60, 0xc9, 0x8e, 0xcf, 0x19, 0xfe, 0x0d, 0xa6,
	0x8e, 0x1e, 0x7f, 0x53, 0x3d, 0x96, 0xbe, 0xbc, 0x11, 0x3e, 0x46, 0xba, 0x69, 0xa7, 0x82, 0xff,
	0x82, 0x95, 0x27, 0x85, 0x33, 0x41, 0x39, 0xed, 0xd1, 0xa0, 0xc4, 0x0e, 0xae, 0x0b, 0x68, 0x14,
	0x03, 0xc4, 0x83, 0xf2, 0x38, 0xb5, 0x6f, 0x78, 0x6e, 0xc6, 0x4e, 0xc5, 0x37, 0xb3, 0x5f, 0xe3,
	0xcf, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x54, 0x73, 0x68, 0x2b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GetJwt(ctx context.Context, in *GetJwtRequest, opts ...grpc.CallOption) (*GetJwtResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetJwt(ctx context.Context, in *GetJwtRequest, opts ...grpc.CallOption) (*GetJwtResponse, error) {
	out := new(GetJwtResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthService/GetJwt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthService/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GetJwt(context.Context, *GetJwtRequest) (*GetJwtResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GetJwt(ctx context.Context, req *GetJwtRequest) (*GetJwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJwt not implemented")
}
func (*UnimplementedAuthServiceServer) Refresh(ctx context.Context, req *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (*UnimplementedAuthServiceServer) Validate(ctx context.Context, req *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GetJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthService/GetJwt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetJwt(ctx, req.(*GetJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthService/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJwt",
			Handler:    _AuthService_GetJwt_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AuthService_Refresh_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _AuthService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authsvc.proto",
}
